### PR TITLE
feat: add support for Casdoor authentication

### PR DESCRIPTION
**Pull request by jakiuncle**
Use [Casdoor](https://github.com/casdoor/casdoor) for auth.

Features:

Support OIDC, OAuth 2.0, SAML, LDAP
With [Casbin](https://casbin.org/) based authorization management, Casdoor supports ACL, RBAC, ABAC, RESTful accessing control models
Front-end and back-end separate architecture, Casdoor supports high concurrency, provides web-based managing UI and have mature solution for springboot project https://casdoor.org/docs/integration/spring-boot
Casdoor supports Github, Google, QQ, WeChat third-party applications login, and support the extension of third-party login with plugins.
Phone verification code, email verification code and forget password features.
Accessing logs auditing and recording.
Casdoor supports integration with existing systems using db sync method, users can transition to Casdoor smoothly.
Casdoor supports mainstream databases: MySQL, PostgreSQL, SQL Server etc, and support the extension of new database with plugins.

Continue:https://github.com/apache/shardingsphere-elasticjob-ui/pull/151

### CODE REVIEW

**Comment by jakiuncle** [comment]
@TeslaCN plz review

**Comment by TeslaCN** [comment]
> @TeslaCN plz review

Thank you. I'll try this soon.

**Review by TeslaCN — CHANGES_REQUESTED** [review]
Hi @jakiuncle 

How can I use the origin authentication? I haven't got any Casdoor in my environment. I've remove the configuration of Casdoor in application.properties, but the UI was still not available.

image

```
[INFO ] 18:28:17.006 [main] o.s.b.c.e.t.TomcatEmbeddedServletContainer - Tomcat started on port(s): 8088 (http)
[INFO ] 18:28:17.009 [main] o.a.s.elasticjob.lite.ui.Bootstrap - Started Bootstrap in 1.991 seconds (JVM running for 2.445)
[INFO ] 18:28:22.996 [http-nio-8088-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring FrameworkServlet 'dispatcherServlet'
[INFO ] 18:28:22.997 [http-nio-8088-exec-1] o.s.web.servlet.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization started
[INFO ] 18:28:23.005 [http-nio-8088-exec-1] o.s.web.servlet.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization completed in 8 ms
[ERROR] 18:28:23.059 [http-nio-8088-exec-1] o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.lang.NullPointerException: null
	at org.casbin.casdoor.service.CasdoorAuthService.parseJwtToken(CasdoorAuthService.java:85)
	at org.apache.shardingsphere.elasticjob.lite.ui.security.AuthenticationFilter.doFilter(AuthenticationFilter.java:79)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shardingsphere.elasticjob.lite.ui.web.filter.CORSFilter.doFilter(CORSFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by jakiuncle** [comment]
In my computer,it have't problem. Can you send a viedo ?

**Comment by jakiuncle** [comment]
If you don't mind, you can add my qq 2509913103 to facilitate our communication

**Comment by TeslaCN** [comment]
[Screencast from 11-02-2022 11:07:37 AM.webm](https://user-images.githubusercontent.com/20503072/199386613-eeb9364d-8575-491c-83b8-3e1b780e4383.webm)

**Comment by jakiuncle** [comment]
You can try login out first , and try it aganin.
I dont konw why you can go main page without logining

**Comment by TeslaCN** [comment]
> You can try login out first , and try it again. I dont konw why you can go main page without logining

All the APIs returned 500, so the frontend could not redirect to login page.

**Comment by jakiuncle** [comment]
Hi i want send a video to you but i can't send a file size more than 10MB in github.
How can I send it to you.

**Comment by TeslaCN** [comment]
> Hi i want send a video to you but i can't send a file size more than 10MB in github.
> How can I send it to you.

You may send to my email wuweijie@apache.org

**Comment by TeslaCN** [comment]
Hi @jakiuncle 
I found the way to reproduce.

1. Start frontend and backend service.
2. Login with account.
3. Restart backend service.
4. Do any operation then got 500. (In master branch, the frontend will redirect to login page automatically)

**Comment by jakiuncle** [comment]
Hi, i fix this error.
You can try it again.

**Comment by TeslaCN** [comment]
Hi @jakiuncle 
[bc239c7](https://github.com/apache/shardingsphere-elasticjob-ui/pull/174/commits/bc239c7c48cbc5ce289b7d85c1673062f290efc8) fixed the problem that cannot redirect to login page. But after login, 500 still occurred. Could you check it again?

image

image

**Comment by jakiuncle** [comment]
Hi,i found why this error appear and fix it.

**Comment by jakiuncle** [comment]
@TeslaCN plz review

**Comment by TeslaCN** [comment]
> @TeslaCN plz review

Sorry for the delay, I will try this soon.

**Comment by tristaZero** [comment]
This feature looks cool, Thanks for your contribution! @jakiuncle 
Once it's merged, maybe we could consider a post to let more users know about it?

**Comment by jakiuncle** [comment]
Yes, it's a good idea.

**Review by TeslaCN — APPROVED** [review]
Thank you for this new feature!

**Comment by jakiuncle** [comment]
Thank you. It's a pleasant cooperation

**Comment by tristaZero** [comment]
@jakiuncle Welcome, @TeslaCN we can discuss the article content and our community editor can help us edit the article and post it on the global channel to help more people know about it. ;-)

**Comment by jakiuncle** [comment]
ok

**Pull request merged**
